version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: kotlin_container_db
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: person
    ports:
      - '3301:3306'
    volumes:
      - ./database/mysql:/var/lib/mysql