spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver.Driver
    url: jdbc:mysql://localhost:3301/person?useTimezone=true&serverTimezone=UTC
    username: user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

